MVCClinica/Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using MVCClinica.Data; //AGREGAR
using System.Data.Entity; //AREGAR


namespace MVCClinica.Controllers
{
    public class MedicoController : Controller
    {

        public ActionResult Index()
        {
            var medico = AdminMedico.Listar();
           
            return View("Index", medico);
        }    //---------> LISTAR TODOS

       // [ActionName("Filter")]
        public ActionResult SearchBySpecialty(string especialidad)
        {
            if (especialidad == null)
            {
                return RedirectToAction("Index");
            }
            List<Medico> medicos = AdminMedico.ListarPorEspecialidad(especialidad);
            return View("Index", medicos);
        }

        public ActionResult Create()
        {
            Medico medico = new Medico();

            return View("Create", medico);
        }


        //Medicos/Create --> POST
        [HttpPost]
        public ActionResult Create(Medico medico)
        {
            if (ModelState.IsValid)
            {
                AdminMedico.Insertar(medico);
                return RedirectToAction("Index");
            }
            return View("Create", medico);
        }

        public ActionResult Detail(int id)
        {
            Medico medico = AdminMedico.GetPorId(id);
            if (medico != null)
            {
                return View("Detail", medico);
            }
            return HttpNotFound();
        }

        //Medicos/Edit --> Get
        public ActionResult Edit(int id)
        {
            Medico medico = AdminMedico.GetPorId(id);
            if (medico != null)
            {
                return View("Edit", medico);
            }
            return HttpNotFound();
        }

        //Medicos/Edit --> POST
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult Edit(Medico medico)
        {
            if (ModelState.IsValid)
            {
                AdminMedico.Modificar(medico);
                return RedirectToAction("Index");
            }
            return View("Edit", medico);
        }

        //Opera/Delete/id --> GET
        //[HttpGet]
        public ActionResult Delete(int id)
        {
            Medico medico = AdminMedico.GetPorId(id);

            if (medico != null)
            {
                return View("Delete", medico);
            }
            else
            {
                return HttpNotFound();
            }
        }

        //Medicos/Delete  --> POST
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {


            AdminMedico.Eliminar(id);

            return RedirectToAction("Index");
        }
    }




}

MVCClinica/Views/Medico/Create.cshtml
@model MVCClinica.Data.Medico

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm("Create", "Medico", FormMethod.Post))
    {
        <div>
            @Html.LabelFor(model => model.Nombre)
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>
        <div>
            @Html.LabelFor(model => model.Apellido)
            @Html.EditorFor(model => model.Apellido)
            @Html.ValidationMessageFor(model => model.Apellido)
        </div>
        <div>
            @Html.LabelFor(model => model.NroMatricula)
            @Html.EditorFor(model => model.NroMatricula)
            @Html.ValidationMessageFor(model => model.NroMatricula)
        </div>
        <div>
            @Html.LabelFor(model => model.Especialidad)
            @Html.EditorFor(model => model.Especialidad)
            @Html.ValidationMessageFor(model => model.Especialidad)
        </div>
        <div>
            @Html.LabelFor(model => model.FechaNacimiento)
            @Html.EditorFor(model => model.FechaNacimiento)
            @Html.ValidationMessageFor(model => model.FechaNacimiento)
        </div>
        <div>
            @Html.LabelFor(model => model.Ciudad)
            @Html.EditorFor(model => model.Ciudad)
            @Html.ValidationMessageFor(model => model.Ciudad)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    }
    @Html.ActionLink("Back to List", "Index", "Medico")
</body>
</html>

MVCClinica/Views/Medico/Delete.cshtml
@model MVCClinica.Data.Medico

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h2>

        Medico Delete

    </h2>
    <p>

        Are you sure you want to delete this Doctor?

    </p>

    @using (Html.BeginForm("Delete", "Medico", FormMethod.Post))
    {
        <fieldset>
             <legend>

                Doctor Delete

             </legend>


            <div class="display-label">

                @Html.DisplayNameFor(model => model.Nombre)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.Nombre)

            </div>


            <div class="display-label">

                @Html.DisplayNameFor(model => model.Apellido)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.Apellido)

            </div>

            <div class="display-label">

                @Html.DisplayNameFor(model => model.NroMatricula)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.NroMatricula)

            </div>

            <div class="display-label">

                @Html.DisplayNameFor(model => model.Especialidad)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.Especialidad)

            </div>

            <div class="display-label">

                @Html.DisplayNameFor(model => model.FechaNacimiento)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.FechaNacimiento)

            </div>
            <div class="display-label">

                @Html.DisplayNameFor(model => model.Ciudad)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.Ciudad)

            </div>

        </fieldset>



        <p>

            <input type="submit" value="Delete" />
        </p>
     }

    <p>
        @Html.ActionLink("Back to List", "Index", "Medico")
    </p>

</body>
</html>

MVCClinica/Views/Medico/Detail.cshtml
@model MVCClinica.Data.Medico
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detail</title>
</head>
<body>
    <h2>

        Medico Detail

    </h2>
    <p>

        Are you sure you want details ?

    </p>

    @using (Html.BeginForm("Detail", "Medico", FormMethod.Post))
    {
        <fieldset>
            <legend>

                Medico Detail

            </legend>


            <div class="display-label">

                @Html.DisplayNameFor(model => model.Nombre)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.Nombre)

            </div>


            <div class="display-label">

                @Html.DisplayNameFor(model => model.Apellido)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.Apellido)

            </div>

            <div class="display-label">

                @Html.DisplayNameFor(model => model.NroMatricula)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.NroMatricula)

            </div>

            <div class="display-label">

                @Html.DisplayNameFor(model => model.Especialidad)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.Especialidad)

            </div>

            <div class="display-label">

                @Html.DisplayNameFor(model => model.FechaNacimiento)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.FechaNacimiento)

            </div>
            <div class="display-label">

                @Html.DisplayNameFor(model => model.Ciudad)

            </div>
            <div class="display-text">

                @Html.DisplayFor(model => model.Ciudad)

            </div>

        </fieldset>

     }

    <p>
        @Html.ActionLink("Back to List", "Index", "Medico")
    </p>

</body>
</html>

MVCClinica/Views/Medico/Edit.cshtml
@model MVCClinica.Data.Medico

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm("Edit", "Medico", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.Id)
        <div>
            @Html.LabelFor(model => model.Nombre)
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>
        <div>
            @Html.LabelFor(model => model.Apellido)
            @Html.EditorFor(model => model.Apellido)
            @Html.ValidationMessageFor(model => model.Apellido)
        </div>
        <div>
            @Html.LabelFor(model => model.NroMatricula)
            @Html.EditorFor(model => model.NroMatricula)
            @Html.ValidationMessageFor(model => model.NroMatricula)
        </div>
        <div>
            @Html.LabelFor(model => model.Especialidad)
            @Html.EditorFor(model => model.Especialidad)
            @Html.ValidationMessageFor(model => model.Especialidad)
        </div>
        <div>
            @Html.LabelFor(model => model.FechaNacimiento)
            @Html.EditorFor(model => model.FechaNacimiento)
            @Html.ValidationMessageFor(model => model.FechaNacimiento)
        </div>
        <div>
            @Html.LabelFor(model => model.Ciudad)
            @Html.EditorFor(model => model.Ciudad)
            @Html.ValidationMessageFor(model => model.Ciudad)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    }
    @Html.ActionLink("Back to List", "Index", "Medico")
</body>
</html>

MVCClinica/Views/Medico/Index.cshtml
@model IEnumerable<MVCClinica.Data.Medico>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>@Html.ActionLink("Create New", "Create", "Medico")</p>

    @using (Html.BeginForm("SearchBySpecialty", "Medico", FormMethod.Get))
    {

        @Html.TextBox("especialidad",null)
        <input type="submit" value="Get" />
    }
    <table>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Nombre)</th>
            <th>@Html.DisplayNameFor(model => model.Apellido)</th>
            <th>@Html.DisplayNameFor(model => model.NroMatricula)</th>
            <th>@Html.DisplayNameFor(model => model.Especialidad)</th>
            <th>@Html.DisplayNameFor(model => model.FechaNacimiento)</th>
            <th>@Html.DisplayNameFor(model => model.Ciudad)</th>
            <th>Details</th>
            <th>Deletes</th>
            <th>Edits</th>
        </tr>
        @foreach (var item in Model)
        {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
        <td>@Html.DisplayFor(modelItem => item.Apellido)</td>
        <td>@Html.DisplayFor(modelItem => item.NroMatricula)</td>
        <td>@Html.DisplayFor(modelItem => item.Especialidad)</td>
        <td>@Html.DisplayFor(modelItem => item.FechaNacimiento)</td>
        <td>@Html.DisplayFor(modelItem => item.Ciudad)</td>

        <td>
            @Html.ActionLink("Detail", "Detail", new { id = item.Id })
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id })
        </td>
        @*<td>
            @Html.ActionLink("Especialidad", "SearchBySpecialty", new { especialidad = item.Especialidad })*@
        @*</td>*@
    </tr>
        }
    </table>

</body>
</html>